# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20171124_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
