# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='answer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
    ]
