# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_auto_20171209_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='expert_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='interest_count',
            field=models.IntegerField(default=0),
        ),
    ]
