# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 06:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20171124_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answercomment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='nestedcomment',
            old_name='comment',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='questioncomment',
            old_name='comment',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nestedcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questioncomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
