# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171124_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='answercomment',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answercomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nestedcomment',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='nestedcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questioncomment',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questioncomment',
            name='user',
        ),
    ]
