# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171126_1549'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20171126_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerComment',
        ),
        migrations.DeleteModel(
            name='NestedComment',
        ),
        migrations.DeleteModel(
            name='QuestionComment',
        ),
        migrations.AddField(
            model_name='postmanager',
            name='answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_manager', to='posts.Answer'),
        ),
        migrations.AddField(
            model_name='postmanager',
            name='question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_manager', to='posts.Question'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_comments', to='posts.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.PostManager'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
