# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20171126_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmanager',
            name='answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_manager', to='posts.Answer'),
        ),
        migrations.AlterField(
            model_name='postmanager',
            name='question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_manager', to='posts.Question'),
        ),
    ]
