# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_topic_description'),
        ('posts', '0008_auto_20171128_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topics',
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='topics.Topic'),
            preserve_default=False,
        ),
    ]
