# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20171129_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerimage',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_image_set', to='posts.Answer'),
        ),
    ]
