# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 16:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20171130_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
