# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20171130_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='answerimage',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='content',
        ),
        migrations.DeleteModel(
            name='AnswerImage',
        ),
        migrations.AddField(
            model_name='answercontent',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Answer'),
        ),
    ]
