# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20171201_0011'),
        ('posts', '0014_auto_20171201_1455'),
    ]

    operations = [
    ]
