# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 05:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20171201_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuillDeltaOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quill_delta_operation_set', to='posts.Answer')),
            ],
        ),
        migrations.RemoveField(
            model_name='answercontent',
            name='answer',
        ),
        migrations.DeleteModel(
            name='AnswerContent',
        ),
    ]
