# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_topic_description'),
        ('posts', '0017_auto_20171201_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topics',
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ManyToManyField(related_name='questions', to='topics.Topic'),
        ),
    ]
