# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20171201_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='topics',
            new_name='topic',
        ),
    ]
