# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20171202_1443'),
        ('posts', '0021_auto_20171201_2351'),
    ]

    operations = [
    ]
