# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20171204_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quilldeltaoperation',
            old_name='attributes',
            new_name='attributes_value',
        ),
        migrations.RenameField(
            model_name='quilldeltaoperation',
            old_name='text',
            new_name='insert_value',
        ),
        migrations.AddField(
            model_name='quilldeltaoperation',
            name='line_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
