# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_quilldeltaoperation_image_insert_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quilldeltaoperation',
            name='line_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
