# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20171205_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quilldeltaoperation',
            old_name='post',
            new_name='answer',
        ),
    ]
