# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_auto_20171206_0226'),
    ]

    operations = [
        migrations.RenameModel('PostManager', 'CommentPostIntermediate')
    ]
