# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20171206_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpostintermediate',
            name='answer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_post_intermediate', to='posts.Answer'),
        ),
        migrations.AlterField(
            model_name='commentpostintermediate',
            name='question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_post_intermediate', to='posts.Question'),
        ),
    ]
