# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_answer_content_html'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
    ]
