# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-08 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20171208_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
