# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 06:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_question_answer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='quilldeltaoperation',
            name='video_insert_value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
