# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_quilldeltaoperation_video_insert_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content_preview_html',
            field=models.TextField(blank=True),
        ),
    ]
