# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 12:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerbookmark',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='answerdownvote',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='answerupvote',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='baseanswercommentvote',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='basenestedcommentvote',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='basequestioncommentvote',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='questionbookmark',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='questionfollow',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='topicexpertisefollow',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='topicinterestfollow',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='userfollow',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='answerbookmark',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Answer'),
        ),
        migrations.AlterField(
            model_name='answerbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionfollow',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Question'),
        ),
        migrations.AlterField(
            model_name='questionfollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
