# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171124_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_user_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='facebook user id'),
        ),
    ]
