# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:11
from __future__ import unicode_literals

from django.db import migrations
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20171129_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=users.fields.EmailNullField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
