# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 17:08
from __future__ import unicode_literals

from django.db import migrations
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20171130_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='facebook_user_id',
            field=users.fields.CharNullField(blank=True, default=None, max_length=300, null=True, unique=True, verbose_name='facebook user id'),
        ),
    ]
