# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_topic_description'),
        ('users', '0011_auto_20171130_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertiseFollowRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='InterestFollowRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='topicexpertisefollowrelation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='topicexpertisefollowrelation',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topicexpertisefollowrelation',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='topicinterestfollowrelation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='topicinterestfollowrelation',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topicinterestfollowrelation',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='topic_expertise',
            field=models.ManyToManyField(blank=True, related_name='users_with_expertise', through='users.ExpertiseFollowRelation', to='topics.Topic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='topic_interests',
            field=models.ManyToManyField(blank=True, related_name='users_with_interest', through='users.InterestFollowRelation', to='topics.Topic'),
        ),
        migrations.DeleteModel(
            name='TopicExpertiseFollowRelation',
        ),
        migrations.DeleteModel(
            name='TopicInterestFollowRelation',
        ),
        migrations.AddField(
            model_name='interestfollowrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertisefollowrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='interestfollowrelation',
            unique_together=set([('user', 'topic')]),
        ),
        migrations.AlterUniqueTogether(
            name='expertisefollowrelation',
            unique_together=set([('user', 'topic')]),
        ),
    ]
