# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import users.utils.image_resize


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20171203_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.image_resize.user_img_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='thumbnail_image_200',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.image_resize.user_thumb_img_200_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='thumbnail_image_25',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.image_resize.user_thumb_img_25_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='thumbnail_image_50',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.image_resize.user_thumb_img_50_path),
        ),
    ]
