# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20171208_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcredential',
            name='degree_type',
            field=models.CharField(blank=True, choices=[('HS', '고등학교'), ('BA', '학사'), ('MA', '석사'), ('PHD', '박사')], max_length=3),
        ),
    ]
