# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20171211_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='answer_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
