# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20171212_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_salt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
