# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 10:00
from __future__ import unicode_literals

from django.db import migrations
import users.utils.fields
import users.utils.image_path


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_user_password_reset_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumbnail_image_200',
            field=users.utils.fields.DefaultStaticImageField(blank=True, null=True, upload_to=users.utils.image_path.user_thumb_img_200_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='thumbnail_image_25',
            field=users.utils.fields.DefaultStaticImageField(blank=True, null=True, upload_to=users.utils.image_path.user_thumb_img_25_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='thumbnail_image_50',
            field=users.utils.fields.DefaultStaticImageField(blank=True, null=True, upload_to=users.utils.image_path.user_thumb_img_50_path),
        ),
    ]
